name: Deploy React App

on:
  push:
    branches:
      - main  # Change this to your branch name if needed
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Build project
       env: 
         REACT_APP_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
